// Generated by https://quicktype.io
import { Colors } from './colors.model';
import { User } from './user.model';

export interface Board {
  id: string;
  title: string;
  backgroundColor: Colors;
  members: User[];
  lists: List[];
  cards: Card[];
}

export interface List {
  id: number;
  title: string;
  position: number;
  creationAt: string;
  updatedAt: string;
  cards: Card[];
}

export interface Card {
  id: string;
  title: string;
  position: number;
  list: List;
  description: string;
}
